# ===========================================================================
# Project:   Brainslug
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore, :theme => :'brainslug_theme'
